# Generated by Django 4.2.1 on 2023-05-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkGroups',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VkImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField()),
                ('image_id', models.IntegerField()),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.TextField()),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art_parser_app.vkgroups')),
            ],
            options={
                'unique_together': {('album_id', 'image_id')},
            },
        ),
    ]
